export const initialEditorState = [
   {
      __children: ['374', '376', '383', '385', '431', '433'],
      __dir: 'ltr',
      __format: 0,
      __indent: 0,
      __key: 'root',
      __parent: null,
      __type: 'root'
   },
   {
      __type: 'heading',
      __parent: 'root',
      __key: '374',
      __children: ['375'],
      __format: 0,
      __indent: 0,
      __dir: 'ltr',
      __tag: 'h3'
   },
   {
      __type: 'text',
      __parent: '374',
      __key: '375',
      __text: 'Xe hơi điện ở Việt Nam: Cục sạc nhanh ở nhà mới là mấu chốt',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'paragraph',
      __parent: 'root',
      __key: '376',
      __children: ['377', '378', '379', '380', '381', '382'],
      __format: 0,
      __indent: 0,
      __dir: 'ltr'
   },
   {
      __type: 'text',
      __parent: '376',
      __key: '377',
      __text: 'Việt Nam',
      __format: 1,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'text',
      __parent: '376',
      __key: '378',
      __text:
         ' đang đón làn gió xe hơi điện khá mạnh mẽ, khi các hãng bắt đầu “rục rịch” giới thiệu những sản phẩm xe điện của mình. Nhưng khi nhắc đến xe hơi điện, tâm điểm của nhiều người ngắm đến đó là số lượng trạm sạc của xe quá ít hoặc còn nhiều sự hạn chế, cụ thể thì hạ tầng tại Việt Nam chỉ có duy nhất một đơn vị phát triển các trạm sạc là VinFast, và dù là khách hàng của VinFast thì họ cũng còn rụt rè bởi thói quen sử dụng xe xăng đã ăn sâu vào tiềm thức, rất ít những suy nghĩ thay đổi hay thích nghi với cái mới. ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'text',
      __parent: '376',
      __key: '379',
      __text: 'Nhưng có một thứ mà hầu hết anh em đã bỏ quên',
      __format: 1,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'text',
      __parent: '376',
      __key: '380',
      __text: ', đó chính là bộ sạc tại nhà hiện tại cũng có thể ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'text',
      __parent: '376',
      __key: '381',
      __text: 'đáp ứng',
      __format: 16,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'text',
      __parent: '376',
      __key: '382',
      __text:
         ' thời gian sạc đầy pin với hơn 3 tiếng sạc, và với mình thì hiện tại đây mới là mấu chốt mà anh em nên quan tâm.',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'paragraph',
      __parent: 'root',
      __key: '383',
      __children: ['384'],
      __format: 0,
      __indent: 0,
      __dir: 'ltr'
   },
   {
      __type: 'text',
      __parent: '383',
      __key: '384',
      __text: 'dfdsaf',
      __format: 2,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code',
      __parent: 'root',
      __key: '385',
      __children: [
         '386',
         '387',
         '388',
         '389',
         '390',
         '391',
         '392',
         '393',
         '394',
         '395',
         '396',
         '397',
         '398',
         '399',
         '400',
         '401',
         '402',
         '403',
         '404',
         '405',
         '406',
         '407',
         '408',
         '409',
         '410',
         '411',
         '412',
         '413',
         '414',
         '415',
         '416',
         '417',
         '418',
         '419',
         '420',
         '421',
         '422',
         '423',
         '424',
         '425',
         '426',
         '427',
         '428',
         '429',
         '430'
      ],
      __format: 0,
      __indent: 0,
      __dir: 'ltr',
      __language: 'javascript'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '386',
      __text: 'const',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'keyword'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '387',
      __text: ' target ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '388',
      __text: '=',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'operator'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '389',
      __text: ' ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '390',
      __text: '{',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   { __type: 'linebreak', __parent: '385', __key: '391' },

   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '392',
      __text: '  ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '393',
      __text: 'message1',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'literal-property'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '394',
      __text: ':',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'operator'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '395',
      __text: ' ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '396',
      __text: '"hello"',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'string'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '397',
      __text: ',',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   ['398', { __type: 'linebreak', __parent: '385', __key: '398' }],

   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '399',
      __text: '  ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '400',
      __text: 'message2',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'literal-property'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '401',
      __text: ':',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'operator'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '402',
      __text: ' ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '403',
      __text: '"everyone"',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'string'
   },
   ['404', { __type: 'linebreak', __parent: '385', __key: '404' }],

   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '405',
      __text: '}',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '406',
      __text: ';',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   ['407', { __type: 'linebreak', __parent: '385', __key: '407' }],
   ['408', { __type: 'linebreak', __parent: '385', __key: '408' }],

   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '409',
      __text: 'const',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'keyword'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '410',
      __text: ' handler1 ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '411',
      __text: '=',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'operator'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '412',
      __text: ' ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '413',
      __text: '{',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '414',
      __text: '}',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '415',
      __text: ';',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   ['416', { __type: 'linebreak', __parent: '385', __key: '416' }],
   ['417', { __type: 'linebreak', __parent: '385', __key: '417' }],

   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '418',
      __text: 'const',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'keyword'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '419',
      __text: ' proxy1 ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '420',
      __text: '=',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'operator'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '421',
      __text: ' ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '422',
      __text: 'new',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'keyword'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '423',
      __text: ' ',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '424',
      __text: 'Proxy',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'class-name'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '425',
      __text: '(',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '426',
      __text: 'target',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '427',
      __text: ',',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '428',
      __text: ' handler1',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '429',
      __text: ')',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   {
      __type: 'code-highlight',
      __parent: '385',
      __key: '430',
      __text: ';',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0,
      __highlightType: 'punctuation'
   },
   {
      __type: 'paragraph',
      __parent: 'root',
      __key: '431',
      __children: ['432'],
      __format: 0,
      __indent: 0,
      __dir: 'ltr'
   },
   {
      __type: 'text',
      __parent: '431',
      __key: '432',
      __text:
         'Quay lại câu chuyện sạc cho xe điện, bản thân mình cũng đã trực tiếp cầm lái chiếc VinFast VF e34 quãng đường 200 km không cần nạp điện, đây là chiếc xe có quãng đường di chuyển ngắn nhất của VinFast ở thời điểm hiện tại, nhưng nếu là VinFast thì câu chuyện sẽ dễ bị chuyển sang hướng phụ thuộc vào trạm sạc bởi VinFast đầu từ xây dựng mạng lưới trạm sạc, thế nên dù có thể là hành trình từ bắc đến nam cũng có thể đáp ứng, chỉ cần bạn có một chút tính toán trước các điểm sạc điện cho xe là được. Và tất nhiên, bạn phải thay đổi thói quen sử dụng nếu như bạn quan tâm và bị phụ thuộc vào trạm sạc.',
      __format: 0,
      __style: '',
      __mode: 0,
      __detail: 0
   },
   {
      __type: 'paragraph',
      __parent: 'root',
      __key: '433',
      __children: ['435'],
      __format: 0,
      __indent: 0,
      __dir: null
   }
]
